# Generated by Django 3.1.7 on 2021-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='Finder', max_length=100, verbose_name='Sujeito')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Usar SSL')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('server_address', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Endereço do servidor')),
                ('server_port', models.CharField(default='587', max_length=10, verbose_name='Porta do servidor')),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
