# Generated by Django 3.1.7 on 2021-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='alert_email',
            field=models.EmailField(default='renan', max_length=254),
            preserve_default=False,
        ),
    ]
